### PR TITLE
Revamped Lawnfeed page

### PR DESCRIPTION
**Pull request by sicrs**

### CODE REVIEW

**Comment by msfjarvis** [comment]
It's usually good to link a live demo of such changes to speed up the review process :)

**Comment by nyancrimew** [comment]
@sicrs Could probably do with our logo at the top, to make it look even less shady, but good work otherwise!

**Comment by nyancrimew** [comment]
@MSF-Jarvis https://sicrs.github.io/lawnchair.info/getlawnfeed.html

**Comment by divadsn** [comment]
The seperator between the download button and donation info is required tho, otherwise looks kinda good to me, but still I ask if the download page should be full blown with fancy CSS :grimacing:

**Review by nyancrimew — APPROVED** [review]
Looks good to me now

**Comment by sicrs** [comment]
@divadsn I'll try to tone down the css as much as possible.

**Comment by divadsn** [comment]
Merging this for now

**Pull request merged**
