### PR TITLE
Update website

### PR DESCRIPTION
**Pull request by SuperDragonXD**
Updates the outdated website, a lot.

A preview can be found here: https://lawnchair-launcher-site.glitch.me/ (note that analytics aren't in the preview, but have been re-added here)

The UI is similar to the `next` branch, but this is just a static site.

### CODE REVIEW

**Comment by SuperDragonXD** [comment]
@patrykmichalik ready for review! (sorry for ping)

**Review by ghost — CHANGES_REQUESTED** [review]
Thanks a bunch for taking the time to do all this! A couple of suggestions for the hero section:

1. When the page is loading, a “Download Lawnchair” button is displayed for a split second before the three cards appear. I’d suggest avoiding this flash and applying a solution similar to the one at https://lawnchair.app/downloads.
2. On wide displays, the background becomes entirely blue. I suggest aligning the background image such that the green area is always visible.

    image
3. The three cards appear to be further right than they should be.

    image image

4. The layout of each of the three cards seems to change earlier than necessary. Below, there is still enough room for the buttons to be on the right. I’d say such a layout is preferential.

    image

5. I would suggest making the card for Lawnchair more prominent than the other two. A solution simliar to the one at https://lawnchair.app/downloads would work.

Since I’m going to have a relatively large number of suggestions, feel free to let me know if you’d rather we applied the edits ourselves. The changes from this PR can always be merged into a feature branch. Thanks again!

**Comment by SuperDragonXD** [comment]
> 1. When the page is loading, a “Download Lawnchair” button is displayed for a split second before the three cards appear. I’d suggest avoiding this flash and applying a solution similar to the one at https://lawnchair.app/downloads

Actually, I made that so that non-JS users could still download Lawnchair... But maybe you could just implement it a better way.

> Since I’m going to have a relatively large number of suggestions, feel free to let me know if you’d rather we applied the edits ourselves. The changes from this PR can always be merged into a feature branch. Thanks again!

You could do that (I think I enabled "allow edits by maintainers"). That could prolly quicken things up so you don't have to wait on me for changes.

**Comment by SuperDragonXD** [comment]
Sorry for late reply, but I did some of them. Also regarding your second question, I'll try to do them and I'll note if I can't do it (instead of making you do those changes)

Request 1: Maybe make "Download Lawnchair" a button that does these:
* If you have JS, show the 3 cards
* If you don't have JS, simply link to the wiki.

Request 2: It's kinda hard/impossible to do that, so I opted for a gradient instead
Request 3: Done!
Request 4: Also done!
Request 5: Should I merge the card with the logo/etc?

**Comment by ghost** [comment]
Cheers for applying the edits! Your proposed way of handling this sounds good to me. Iʼll list my ideas and potentially apply some changes of my own at the end.

Regarding point 1, I donʼt think we have to support browsers with JavaScript disabled. Practically all websites use JavaScript nowadays, and many large websites simply refuse to load if JavaScript is off. Itʼs a core part of the web.

Regarding point 2, I think it should be possible to achieve this with `background-position`. Iʼll gladly look into it later on.

Regarding point 5, I think itʼd be enough to use a slightly different style for the first card. In the case of https://lawnchair.app/downloads, the first card has a larger title and text buttons.

**Comment by SuperDragonXD** [comment]
Have done Point 1 & 5.

**Review by ghost — CHANGES_REQUESTED** [review]
Cheers! I would suggest ensuring greater consistency in terms of the width of the content. This would mean using a common container width for the content of the footer and the two sections in the area with the white background. For text, the optimal line length is 60 to 80 characters.

image

**Comment by SuperDragonXD** [comment]
Made that change, but I'm not sure on what's the best common width for them. Made the maximum width `750px`. Thoughts?

**Comment by ghost** [comment]
Cheers! How about something like 840 px? I think the content could benefit from being slightly wider. Additionally, 840 px is a multiple of 12 px, and numbers that are divisible by 12 with no remainder are commonly used for container widths.

**Comment by SuperDragonXD** [comment]
Done that.

**Comment by ghost** [comment]
Thanks! As weʼve discussed, Iʼll apply a couple of edits and merge the pull request shortly. Cheers for contributing! We greatly appreciate the help.

**Comment by ghost** [comment]
I regret to let you know that since I’ll no longer be contributing to Lawnchair ([more info](https://t.me/lawnchairci/1557)), I won’t be able to attend to this pull request anymore. That is, Iʼll not be making edits to it or merging it. I hope another team member will handle it. Thank you for your interest in contributing!

**Pull request merged**
